template:

  #Spring
  spring:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      show-sql: true
    datasource:
      url: jdbc:h2:mem:testdb2
      username: sa
      password:
    h2:
      console:
        enabled: true
        path: /h2-console
  #Redis
  redis:
    #hostname do Redis, quando usando docker, Ã© o IPAdress fornecido pelo comando "docker inspect <nomeContainer>.
    hostname: 172.17.0.2
    port: 6379

server:
  port: ${port:8445}



